export { default as AuthPage } from './AuthPage'
export { default as HomePage } from './HomePage'
export { default as Product } from './Product'
export { default as CartPage } from './CartPage'
export { default as ProfilePage } from './ProfilePage'
export { default as CheckOutPage } from './CheckOutPage'